### PR TITLE
fix: correctly prioritize the host's gschema instead of the flatpak's

### LINKED ISSUE #25: Host's dconf variable **defaults** are shadowed by the Flatpak environment
I've discovered that defaults in the host's gschema database are being shadowed by the Flatpak environment of dconf-editor, so it observes the Flatpak's defaults instead of the host's defaults. Could it be solvable by changing the priority order of gschema folders, perhaps?

## Example of DEFAULT values before setting anything in the host's dconf database:

- **Host:**

```sh
[johnny@fedora ~]$ gsettings get org.gnome.desktop.interface gtk-theme
'adw-gtk3'
[johnny@fedora ~]$ gsettings get org.gnome.desktop.interface color-scheme
'prefer-light'
```

- **dconf editor Flatpak:**

image

---

## Forced values work.

Now let's set a forced value instead of relying on the default value:

- **Host:**

```sh
[johnny@fedora ~]$ gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
[johnny@fedora ~]$ gsettings get org.gnome.desktop.interface color-scheme
'prefer-dark'
```

- **dconf editor Flatpak:**

image

### PR DESCRIPTION
**Pull request by Arcitec**
The environment variable was being built in the wrong order, and was putting the Flatpak's data locations as the highest priority. This meant that dconf-editor showed *completely wrong* values for most settings in dconf, since it was looking at the default Flatpak environment rather than the host's dconf environment!

This has now been fixed to use the correct priority, putting all host paths first, and then the Flatpak's default locations after that as fallbacks.

Closes #25.

### CODE REVIEW

File: start-dconf-editor.sh [hunk 1]
```diff
@@ -17,9 +19,17 @@ for dir in "${host_data_dirs[@]}"; do
...
 
+# We MUST prepend the host's data dirs BEFORE the Flatpak environment's own dirs,
+# otherwise data (such as default values) load in the wrong order and would then
+# incorrectly prefer the Flatpak's internal defaults instead of the host's defaults!
+if [[ ! -z "${HOST_XDG_DATA_DIRS}" ]]; then
+  XDG_DATA_DIRS="${HOST_XDG_DATA_DIRS:1}:${XDG_DATA_DIRS}"
+fi
+
 export XDG_DATA_DIRS
+#echo "Using XDG_DATA_DIRS=${XDG_DATA_DIRS}"
```
Comment (TingPing) [inline start-dconf-editor.sh:34]:
```suggestion
```

Comment (Arcitec) [reply start-dconf-editor.sh]: @TingPing Fixed! I left that on purpose to make it easy for maintainers to debug by just uncommenting that, but I can agree that it's pointless. :)
